language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      
    - os: osx
      compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - gcc-multilib 
      - g++-multilib
      - clang

script:
  - echo "Build done!"
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd ./build/projects/gmake-linux; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cd ./build/projects/gmake-osx; fi
  - make config=debug32
  - make config=debug64
  - make config=release32
  - make config=release64

branches:
  only:
    - master

notifications:
  email: false

osx_image: xcode9.3