language: cpp
matrix:
  include:
    - os: linux
      language: cpp
      compiler: gcc
      dist: trusty
      before_install:
        # C++11
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq

      install: 
        # C++11
        - sudo apt-get install -qq g++-5
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

      script:
        - cd ./build/projects/gmake-linux
        - make config=debug64
      
    - os: osx
      compiler: clang
      script:
        - cd ./build/projects/gmake-osx;
        - make config=debug64
        - make config=release64

  allow_failures:
    - os: osx



branches:
  only:
    - master

notifications:
  email: false

osx_image: xcode9.3