language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      script:
        - cd ./build/projects/gmake-linux
        - make config=debug64
        - make config=release64
      
    - os: osx
      compiler: clang
      script:
        - cd ./build/projects/gmake-osx;
        - make config=debug64
        - make config=release64

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - gcc-multilib 
      - g++-multilib
      - clang



branches:
  only:
    - master

notifications:
  email: false

osx_image: xcode9.3